const data = [
  { country: "us", value: 27 },
  { country: "gb", value: 1 },
  { country: "ca", value: 2 },
  { country: "cn", value: 3 },
  { country: "hr", value: 4 },
  { country: "nl", value: 5 },
  { country: "eg", value: 6 },
  { country: "fr", value: 7 },
  { country: "gr", value: 8 },
  { country: "in", value: 9 },
  { country: "ie", value: 10 },
  { country: "it", value: 11 },
  { country: "jm", value: 12 },
  { country: "jp", value: 13 },
  { country: "ke", value: 14 },
  { country: "my", value: 15 },
  { country: "mx", value: 16 },
  { country: "ma", value: 17 },
  { country: "pl", value: 18 },
  { country: "pt", value: 19 },
  { country: "ru", value: 20 },
  { country: "es", value: 21 },
  { country: "th", value: 22 },
  { country: "tn", value: 23 },
  { country: "tr", value: 24 },
  { country: "unk", value: 25 },
  { country: "vn", value: 26 },
];

export default data;
